services:
  # Aplicación Laravel
  app:
    build: .
    container_name: laravel-notas-app
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./resources:/var/www/html/resources
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_notas
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret123
    depends_on:
      - db
    networks:
      - laravel-network

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: laravel-notas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_notas
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: rootsecret123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  # phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-notas-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: secret123
    depends_on:
      - db
    networks:
      - laravel-network

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge